import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Define the links separately. This way it's easier to add or remove links. Also, it's useful if we want to add more functionality or data to each link.
const links = [
  { title: "About", url: "/about", access: "public" },
  { title: "Dashboard", url: "/dashboard", access: "admin" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Base background color and base text color are black (bg-black) and white (text-white) correspondigly, using Tailwind classes. */}
      <body className={raleway.className + " bg-black text-white px-10"}>
        <Navbar links={links} />
        {children}
      </body>
    </html>
  );
}
